from pydantic import BaseModel, Field
from typing import List, Optional, Dict, Any

class QueryRequest(BaseModel):
    question: str = Field(..., description="The question to ask the RAG system", example="What is pgvector?")
    search_mode: str = Field("vector", description="Search mode: 'vector', 'keyword', or 'hybrid'", example="hybrid")
    use_rescoring: bool = Field(True, description="Whether to use LLM rescoring", example=True)
    use_stream: bool = Field(False, description="Whether to stream the response", example=False)
    top_k: int = Field(3, description="Number of context chunks to use", example=3)
    filters: Optional[Dict[str, Any]] = Field(None, description="Metadata filters (e.g., {'file_type': 'pdf'})", example={"file_type": "pdf"})

class ContextChunk(BaseModel):
    text: str = Field(..., example="This is a chunk of text from the document.")
    document_name: str = Field(..., example="Report2025.pdf")
    chunk_index: int = Field(..., example=0)
    score: Optional[float] = Field(None, example=0.85)
    file_type: Optional[str] = Field(None, example="pdf")

class QueryResponse(BaseModel):
    answer: str = Field(..., example="The answer generated by the LLM.")
    search_query: str = Field(..., example="optimized search query")
    search_mode: str = Field(..., example="hybrid")
    contexts: List[ContextChunk]
    is_stream: bool = False

class TextIngestRequest(BaseModel):
    text: str = Field(..., description="Raw text to ingest", example="This is some sample text to be indexed.")
    document_name: str = Field(..., description="Name for the ingested document", example="Manual_Entry_1")
    chunk_size: int = Field(1000, description="Size of each chunk", example=1000)
    overlap: int = Field(200, description="Overlap between chunks", example=200)
    metadata: Optional[Dict[str, Any]] = Field(None, description="Additional metadata", example={"author": "admin"})

class DocumentInfo(BaseModel):
    document_name: str = Field(..., example="doc1.pdf")
    chunk_count: int = Field(..., example=15)
    file_type: str = Field(..., example="pdf")

class EvaluationRequest(BaseModel):
    dataset_path: str = Field("data/eval/golden_set.json", description="Path to the evaluation dataset", example="data/eval/golden_set.json")

class EvaluationResponse(BaseModel):
    status: str = Field(..., example="success")
    md_report: str = Field(..., example="reports/eval_20260409.md")
    csv_report: str = Field(..., example="reports/eval_20260409.csv")
    metrics: Dict[str, Any] = Field(..., example={"faithfulness": 0.88, "answer_relevancy": 0.92})
