import { test, expect } from '@playwright/test';
import path from 'path';
import fs from 'fs';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

test.describe('Document Preview E2E', () => {
  const fileName = 'playwright-test-preview.txt';
  const fileContent = 'This is content generated by Playwright for preview testing.';
  const filePath = path.join(__dirname, fileName);

  test.beforeAll(() => {
    fs.writeFileSync(filePath, fileContent);
  });

  test.afterAll(() => {
    if (fs.existsSync(filePath)) {
      fs.unlinkSync(filePath);
    }
  });

  test('should upload, preview, and delete a document', async ({ page }) => {
    // Debugging: Capture browser logs
    page.on('console', msg => {
      if (msg.type() === 'error' || msg.type() === 'warning') {
        console.log(`BROWSER ${msg.type().toUpperCase()}: ${msg.text()}`);
      }
    });
    page.on('pageerror', err => console.log(`BROWSER RUNTIME ERROR: ${err.message}`));

    // 1. Navigate to the app
    await page.goto('/');
    
    // Wait for the app to hydrate (root should not be empty)
    await expect(page.locator('#root')).not.toBeEmpty({ timeout: 30000 });

    // Wait for the app to render the main UI
    await expect(page.getByText(/Data Sources/i)).toBeVisible({ timeout: 20000 });
    
    // 2. Upload a document
    const uploadButton = page.getByRole('button', { name: /UPLOAD NEW/i });
    await expect(uploadButton).toBeVisible();

    const fileChooserPromise = page.waitForEvent('filechooser');
    await uploadButton.click();
    const fileChooser = await fileChooserPromise;
    await fileChooser.setFiles(filePath);

    // 3. Wait for the document to appear in the list and be INDEXED
    // The fileName is in the table/list
    const row = page.locator('tr, div.rounded-xl').filter({ hasText: fileName }).first();
    await expect(row).toBeVisible({ timeout: 25000 });
    
    // Wait for INDEXED badge
    await expect(row.getByText('INDEXED')).toBeVisible({ timeout: 15000 });

    // 4. Trigger Preview
    // Locate the Eye icon button within that specific row
    const previewButton = row.locator('button').filter({ has: page.locator('svg.lucide-eye') });
    await previewButton.click();

    // 5. Verify Preview Content
    // Modal header should contain filename - target the one in the fixed overlay/modal
    const modal = page.locator('div.fixed.inset-0');
    const modalHeader = modal.locator('h3').filter({ hasText: fileName });
    await expect(modalHeader).toBeVisible({ timeout: 10000 });
    
    // Check for content in pre tag within the modal
    await expect(modal.locator('pre')).toContainText(fileContent, { timeout: 10000 });

    // 6. Close Preview
    await modal.getByRole('button', { name: /Close/i }).click();
    await expect(modal).not.toBeVisible();
    
    // 7. Cleanup: Delete the document
    page.once('dialog', dialog => dialog.accept());
    const deleteButton = row.locator('button').filter({ has: page.locator('svg.lucide-trash2') });
    await deleteButton.click();
    
    // Verify it's gone
    await expect(row).not.toBeVisible({ timeout: 10000 });
  });
});
